apiVersion: v1
kind: Service
metadata:
  name: publisher-service
spec:
  selector:
    app: publisher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Use NodePort se estiver usando o Minikube
