apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
spec:
  selector:
    app: subscriber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer  # Use NodePort se estiver usando o Minikube
