apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-deployment
  labels:
    group: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
        group: backend
    spec:
      containers:
      - name: subscriber
        image: tharbuini/trabalho-final-asa:subscriber
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        - name: PS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-database-url
        envFrom:
        - configMapRef:
            name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
  labels:
    group: backend
spec:
  selector:
    app: subscriber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer 
