apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    group: db
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_URL: postgresql+psycopg2://admin:admin@localhost:5432/postgres