apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: tharbuini/trabalho-final-asa:subscriber
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
spec:
  selector:
    app: subscriber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer  # Use NodePort se estiver usando o Minikube
